#/bin/sh

####
##
## To execute this as a script, run:
##		sh -c 'eval "`cat`"'
## on the target machine, paste whole text from this file, then press CTRL+D.
##
####

set -e
set -x

echo Initializing installer script  >&2

#
# Check user
#
test `id -u` != 0 && echo 'ERROR: Must be root!' && exit 1

#
# Upgrade the system
#
PAGER=cat freebsd-update fetch install
pkg upgrade -y

#
# Set installation root (for tarballs)
#
PKG_PREFIX=${PKG_PREFIX-/usr/local}
